### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by prologic** [tink-ab/login-service#2]
What is this licesed under?

**Comment by JensRantil** [comment]
https://github.com/tink-ab/login-service/blob/master/LICENSE

**Comment by prologic** [comment]
Ahh the reason I didn't see it is because the project doesn't list an
overall license type. Can you set one as such in the project settings?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by JensRantil** [comment]
@prologic I can't find any such setting under "Settings" for this repo. Am I missing something? Could be that Github simply auto-discovers license based on `LICENSE` file and ours doesn't fit any of their templates.

**Comment by prologic** [comment]
Hmmm IIRC I think Github parses our the LICENSE file; but I notice you have
a rather strange looking/formatted one :D Not sure tbh I'd have to go look
at the Github docs on this


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
